spring:
  datasource:
    url: jdbc:mysql://localhost:13306/java_gobang?characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml